#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

./vendor/bin/phpstan

# Rodar o phpstan antes de commitar
if [ $? -ne 0 ]; then
  echo "OPA!! Deu ruim aqui com o phpstan... Arruma antes de Continuar... 🚀🚀"
  exit 1
fi

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '.php\{0.1\}$') || true

for FILE in $STAGED_FILES

do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1
    git add "${FILE}"
done
